In [ ]:
import pandas as pd;
s= pd.Series([10,11,12])
s
# s.dtype

dtype('int64')

In [12]:
labels=['A','B','C']
s= pd.Series([10,11,12],labels)
s
# s.index=labels
# s

A    10
B    11
C    12
dtype: int64

In [7]:
print(s[0:2])
print(s['A':'B'])

A    10
B    11
dtype: int64
A    10
B    11
dtype: int64

In [21]:
s.iloc[2:3]

C    12
dtype: int64

In [22]:
s.loc["A":"C"]

A    10
B    11
C    12
dtype: int64

In [24]:
Fruit_portion = {
    "mango" : 2.0,
    "Apple":0.1,
    "PineApple" : 0.5,
    "Avocardo" : 1.2,
    "Grapes" : 1.5,
    "Kiwi" : 2.1,
    "Cherry" : 1.8,
    "BlackBerry" : 0.6,
    "A": 1.1,
    "B" : 1.2
}

s2= pd.Series(Fruit_portion,name="portion");
s2

mango         2.0
Apple         0.1
PineApple     0.5
Avocardo      1.2
Grapes        1.5
Kiwi          2.1
Cherry        1.8
BlackBerry    0.6
A             1.1
B             1.2
Name: portion, dtype: float64

In [30]:
# s2[s2>1]
# s2[(s2>0.5) & (s2<2.0)]
# s2[(s2>0.5) | (s2<2.0)]
s2[~(s2>1)]

Apple         0.1
PineApple     0.5
BlackBerry    0.6
Name: portion, dtype: float64

In [32]:
s2["mango"]

np.float64(2.0)

In [59]:
import numpy as np;

data = {
    "name": np.array(["A", "B", "C", "D"]),
    "marks": np.array([ np.nan, 72, 72, 64]),
    "age": np.array([21, 22, np.nan, 23])
}

df = pd.DataFrame(data);
df

  name  marks   age
0    A    NaN  21.0
1    B   72.0  22.0
2    C   72.0   NaN
3    D   64.0  23.0

In [ ]:
df.head()
#  print all the table

  name  marks   age
0    A    NaN  21.0
1    B   72.0  22.0
2    C   91.0   NaN
3    D   64.0  23.0

In [ ]:
df.head(3)
#  print 0 to 3

  name  marks   age
0    A    NaN  21.0
1    B   72.0  22.0
2    C   91.0   NaN

In [72]:
df.tail(1)

  name  marks   age
3    D   64.0  23.0

In [ ]:
df.tail(3)
#  print from 3 to 1 tala adu

  name  marks   age
1    B   72.0  22.0
2    C   72.0   NaN
3    D   64.0  23.0

In [ ]:
df.iloc[1:3]
# print 1  to 2

  name  marks   age
1    B   72.0  22.0
2    C   91.0   NaN

In [ ]:
df.loc[1:3]
# print 1 to 3

  name  marks   age
1    B   72.0  22.0
2    C   91.0   NaN
3    D   64.0  23.0

In [41]:
df['marks']

0     NaN
1    72.0
2    91.0
3    64.0
Name: marks, dtype: float64

In [43]:
df[['name','marks']]

  name  marks
0    A    NaN
1    B   72.0
2    C   91.0
3    D   64.0

In [46]:
df.drop('age',axis=1)

  name  marks
0    A    NaN
1    B   72.0
2    C   91.0
3    D   64.0

In [ ]:
# df.shape[4]

# df.info()

IndexError: tuple index out of range

In [66]:
df.describe()

           marks   age
count   3.000000   3.0
mean   69.333333  22.0
std     4.618802   1.0
min    64.000000  21.0
25%    68.000000  21.5
50%    72.000000  22.0
75%    72.000000  22.5
max    72.000000  23.0

In [67]:
df["marks"].unique();
df
# df

  name  marks   age
0    A    NaN  21.0
1    B   72.0  22.0
2    C   72.0   NaN
3    D   64.0  23.0

In [69]:
df.isnull().sum()
df

  name  marks   age
0    A    NaN  21.0
1    B   72.0  22.0
2    C   72.0   NaN
3    D   64.0  23.0